### ISSUE TITLE
TypeError when running block in a service.

### ISSUE THREAD

**Issue by kevincrabbe** [nio-blocks/reddit#4]
Error Details:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/niocore/core/service/launcher.py", line 92, in configure
    self._configure_service(self._context)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/niocore/core/service/launcher.py", line 141, in _configure_service
    self._service.do_configure(service_context)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nio/util/runner.py", line 79, in do_configure
    self.configure(context)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nio/service/base.py", line 163, in configure
    block_context)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nio/service/base.py", line 194, in _create_and_configure_block
    block.do_configure(block_context)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nio/util/runner.py", line 79, in do_configure
    self.configure(context)
  File "/Users/kevin/first_project/blocks/reddit/reddit_subreddit_block.py", line 60, in configure
    self.init_post_id(query)
  File "/Users/kevin/first_project/blocks/reddit/reddit_subreddit_block.py", line 87, in init_post_id
    headers = self._get_headers()
  File "/Users/kevin/first_project/blocks/reddit/reddit_subreddit_block.py", line 140, in _get_headers
    "Authorization": "bearer " + self.token,
TypeError: Can't convert 'NoneType' object to str implicitly
```

**Comment by kevincrabbe** [comment]
Using Python 3.5

**Comment by kevincrabbe** [comment]
Issue originates with httpRESTPolling Block not with SubReddit block
